### ISSUE TITLE
Testing data set

### ISSUE THREAD

**Issue by sebkur** [google/hrx#5]
I recently had the idea of creating a plain text archive format, searched the web and found this project, which is precisely what I was looking for. I needed a Java implementation though and decided I would implement an I/O library for Java for hrx instead of rolling my own custom archive format. I just found the time to do it yesterday and here are the results: https://github.com/topobyte/hrx-java

I implemented a test case for each of the example files, however I'm not 100% sure my implementation behaves exactly as specified / the same as the ruby implementation concerning trailing newlines. I think it would be very useful to have a set of testing files as a reference for current and future implementing developers. As a start, how about creating an extracted version of all the example files, i.e. we could have a directory `extracted-examples` containing a directory `X` for each `X.hrx` from `examples`. I'm not too fluent in setting up ruby and gems, so I would appreciate if you could create such a reference data set by unpacking all examples into corresponding directories and pushing it here. Thanks!

**Comment by nex3** [comment]
Great idea! I'll send out a PR momentarily.

**Comment by sebkur** [comment]
Thanks, that helped getting the newline handling right
