### ISSUE TITLE
List of implementations

### ISSUE THREAD

**Issue by sebkur** [google/hrx#6]
What do you think about having a list of implementations somewhere in the README?

I have found those so far:
* Ruby: https://github.com/google/hrx-ruby
* Python: https://github.com/rebeccajae/hrx.py
* JavaScript: https://github.com/rebeccajae/hrx.js
* Rust: https://github.com/nabijaczleweli/hrx.rs
* Java: https://github.com/topobyte/hrx-java

Are there any more that you're aware of?

**Comment by nex3** [comment]
Another good suggestion!
